### ISSUE TITLE
Consider including the tests and readme in future release tarballs

### ISSUE THREAD

**Issue by bowlofeggs** [mlocati/cldr-to-gettext-plural-rules#11]
Hello!

I am working on packaging this library for Fedora. Fedora packages often run test suites when possible, but I noticed that the release tarballs in this library do not seem to include the tests. Additionally, it would be nice to include the Readme file as documentation.

Thanks!

**Comment by mlocati** [comment]
I'd prefer to keep the downloadable ZIP archive as clean as possible (it's used by composer, and 99% of users does not need the tests and all the extra files [excluded from the archive](https://github.com/mlocati/cldr-to-gettext-plural-rules/blob/master/.gitattributes).)

To have a local copy of everything that's in the repository (so, tests stuff and readme), you could do something like this:

```sh
git clone \
    --branch 2.1.3\
    --depth 1\
    https://github.com/mlocati/cldr-to-gettext-plural-rules.git cldr-to-gettext-plural-rules

rm -rf \
    cldr-to-gettext-plural-rules/.git* \
    cldr-to-gettext-plural-rules/.travis.yml
```

**Comment by bowlofeggs** [comment]
I need to provide a URL in my spec file to a tarball of the sources I am using to build the package which would preferably come from a trusted source (like the project upstream). So unfortunately, I won't be able to use git to get the sources in the spec file. Perhaps I could use git to generate the sources and host them myself somewhere.

Thanks for considering the issue!

Just in case you are interested, I've submitted a package review for Fedora here:

https://bugzilla.redhat.com/show_bug.cgi?id=1413434
