### ISSUE TITLE
gettext/gettext dependency

### ISSUE THREAD

**Issue by oscarotero** [mlocati/cldr-to-gettext-plural-rules#7]
Hi. I've added this package as a gettext/gettext dependency, as you can see in this branch: https://github.com/oscarotero/Gettext/tree/gettext-languages

The main benefit of this is do not reinvent the wheel. If this package can provide all information about plurals, it makes no sense that gettext/gettext does the same.
The main drawback is that there is now a dependency, so it's more difficult to install it without composer I think i'ts an acceptable drawback, but the autoloader.php file only load the gettext/gettext classes but not the gettext/languages classes, I guess this package can provide its own autoloader.php to use this code  in any non-composer project:
```php
require_once __DIR__.'/gettext/src/autoloader.php';
require_once __DIR__.'/cldr-to-gettext-plural-rules/src/autoloader.php';
```

Other issue that I found is the namespace. The vendor in composer is "gettext/languages" but the namespace is `GettextLanguages`. I suggest to use the namespace `Gettext\Languages`.

:smile:

**Comment by mlocati** [comment]
Hey Oscar, thank you!
Yes, this package already has an autoloader file.
About the namespace... Yes, your suggestion is much better than what I did. I'll change the namespace ASAP.

**Comment by oscarotero** [comment]
>  Yes, this package already has an autoloader file.

Oops, my fault. I've suggested this before looking if the file existed.
